#!/usr/bin/env node
/**
 * Generate VAPID keys into repo-root .env if missing.
 * Usage: node scripts/ensure-vapid.mjs
 */
import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const envPath = resolve(root, '.env');
const examplePath = resolve(root, '.env.example');

function loadWebPush() {
  const require = createRequire(import.meta.url);
  const candidates = [
    resolve(root, 'apps/backend/node_modules/web-push'),
    resolve(root, 'node_modules/web-push'),
  ];
  for (const c of candidates) {
    try {
      return require(c);
    } catch {
      // continue
    }
  }
  throw new Error(
    'web-push not found. Run: pnpm --filter @trading-os/backend add web-push',
  );
}

function parseEnv(text) {
  const map = new Map();
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (m) map.set(m[1], m[2]);
  }
  return map;
}

if (!existsSync(envPath)) {
  if (existsSync(examplePath)) {
    copyFileSync(examplePath, envPath);
    console.log('Created .env from .env.example');
  } else {
    writeFileSync(envPath, '', 'utf8');
    console.log('Created empty .env');
  }
}

const existing = readFileSync(envPath, 'utf8');
const vars = parseEnv(existing);
if (vars.get('VAPID_PUBLIC_KEY') && vars.get('VAPID_PRIVATE_KEY')) {
  console.log('VAPID keys already present in .env — nothing to do.');
  process.exit(0);
}

const webpush = loadWebPush();
const keys = webpush.generateVAPIDKeys();
const subject = vars.get('VAPID_SUBJECT') || 'mailto:trading-os@localhost';

const block = [
  '',
  '# Web Push (generated by scripts/ensure-vapid.mjs)',
  `VAPID_PUBLIC_KEY=${keys.publicKey}`,
  `VAPID_PRIVATE_KEY=${keys.privateKey}`,
  `VAPID_SUBJECT=${subject}`,
  '',
].join('\n');

writeFileSync(envPath, existing.replace(/\s*$/, '') + block, 'utf8');
console.log('Wrote VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT to .env');
